### PR TITLE
Add Yellow Markers for Warnings

### PR DESCRIPTION
**Pull request by mattlyons0**
Simply add a different (yellow) colored marker for warnings.

Thank you for this package, its been super useful for me!

Screenshot

### CODE REVIEW

**Comment by mattlyons0** [comment]
I'm using ESLint which has both warning and error types but I think its worth considering a way for users to specify types and their corresponding colors (as other linters may have more types)

**Comment by mattlyons0** [comment]
Since you are actually pulling in diagnostics messages I added a Info marker. Additionally an idea at solving https://github.com/surdu/scroll-marker/issues/4 is to add transparency to the markers so overlayed ones will blend

**Comment by surdu** [comment]
Holy cow of coincidence! It appears I was not watching my own repo 😅 and didn't get any notifications of you opening a pull request, just came by the repo with other reasons. Fixed that ...

I thought about this, but I forgot why I decided to go with all red ... 😖 

Anyway, if you could please choose a more orange color for the warning layer, to not be confused with search results, I would gladly merge your changes. My suggestion would be #fd8926.

Thank you and sorry of the late response 😞

**Comment by mattlyons0** [comment]
No problem, I updated the color to that.

**Comment by surdu** [comment]
Thank you for your contribution!

**Pull request merged**
